name: Run tests
on: [push, pull_request]
env:
  GO_VERSION: 1.18
jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        run: |
          make test
