name: Run tests
on: [push, pull_request]
env:
  GO_VERSION: 1.18
jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        run: |
          make test
