name: Run tests
on: [push, pull_request]
env:
  GO_VERSION: 1.23
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        run: |
          make test
