name: Run tests
on: [push, pull_request]
env:
  GO_VERSION: 1.18
jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        run: |
          make test
